# Generated by Django 5.2.8 on 2025-11-25 10:16

import diagnosis.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=diagnosis.models.audio_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_transcript', models.TextField(help_text='What the AI heard')),
                ('target_transcript', models.TextField(help_text='What should have been said')),
                ('mismatched_chars', models.JSONField(default=list, help_text='List of stuttered character sequences')),
                ('mismatch_percentage', models.FloatField(help_text='Percentage of mismatched characters', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ctc_loss_score', models.FloatField(help_text='CTC Loss score - lower is better')),
                ('stutter_timestamps', models.JSONField(default=list, help_text='List of (start, end) timestamp tuples for stutter events')),
                ('total_stutter_duration', models.FloatField(default=0.0, help_text='Total duration of stuttering in seconds')),
                ('stutter_frequency', models.FloatField(default=0.0, help_text='Stutters per minute')),
                ('severity', models.CharField(choices=[('none', 'No Stuttering'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('analysis_duration_seconds', models.FloatField(help_text='How long analysis took')),
                ('model_version', models.CharField(default='facebook/mms-1b-all', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='diagnosis.audiorecording')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='audiorecording',
            index=models.Index(fields=['patient', '-recorded_at'], name='diagnosis_a_patient_54a4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='audiorecording',
            index=models.Index(fields=['status'], name='diagnosis_a_status_25d407_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['recording'], name='diagnosis_a_recordi_4a8c07_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['severity'], name='diagnosis_a_severit_ca3e6d_idx'),
        ),
    ]
